[package]
name = "enclave-protocol"
version = "0.6.0"
authors = ["Crypto.com <chain@crypto.com>"]
description = "Requests and responses exchanges over ZMQ between chain-abci app "
readme = "../README.md"
edition = "2018"

[features]
default = ["chain-core/default"]
edp = ["chain-core/edp", "secp256k1zkp/edp"]
mesalock_sgx = ["sgx_tstd", "secp256k1zkp/sgx", "chain-core/mesalock_sgx", "chain-tx-validation/mesalock_sgx"]

[dependencies]
chain-core = { path = "../chain-core", default-features = false }
chain-tx-validation = { path = "../chain-tx-validation", default-features = false }
parity-scale-codec = { version = "1.3", default-features = false, features = ["derive"] }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "f8759809f6e3fed793b37166f7cd91c57cdb2eab" }
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
